### ISSUE TITLE
Downloaded report contains details for the second .fit file twice

### ISSUE THREAD

**Issue by h4l** [dblodgett-cycling/dualR#1]
In the downloaded version of the report, the details from the first .fit file aren't shown and the second .fit file's details are shown twice. 

This is the downloaded report: https://bl.ocks.org/h4l/raw/1e1c69af7cc4866c8e89fbe71c53f2d9/

A screenshot of the comparison before I downloaded the report:
![image](https://user-images.githubusercontent.com/146503/107076185-fe33a780-67e2-11eb-884b-bb9bb410c6f5.png)

**Comment by dblodgett-cycling** [comment]
There it is. https://github.com/dblodgett-cycling/dualR/blob/master/app.R#L227
