### ISSUE TITLE
Source code for indieVelo .fit files

### ISSUE THREAD

**Issue by NordicFlyer1** [dblodgett-cycling/dualR#10]
Do you have the source code to read the indieVelo .fit files with trainer device and power meter device files recorded simultaneously.? Can you post it here? I would like to compare my own files from indieVelo independently without using third party web sites. Thank you.

**Comment by dblodgett-cycling** [comment]
The source is all in this repository. 

https://github.com/dblodgett-cycling/dualR/blob/master/R/ has all the package files and you’ll find other important parts of the app here. https://github.com/dblodgett-cycling/dualR/blob/master/utils.R

app.R has the rest of the shiny app. 

The actual fit file reads are done with FITfileR.
